### ISSUE TITLE
Inquiry about state of this project

### ISSUE THREAD

**Issue by jmw182** [SachsLab/CereStimWrapper#1]
Hi @cboulay, I am just wondering if this project is in a working state and if it's something your lab is actively using? 

I am currently working on my own python bindings for the cerestim using pybind11, but I just found this repo which looks like it may achieve the same purpose.

**Comment by cboulay** [comment]
Hi Jeff, yes we are actively using it. We use it in https://github.com/CerebusOSS/CereStimDBS

I don't love SWIG, but it seems like a good fit in this case because it's so simple. That's why I haven't had to update the code in so long. I suppose I could mint some new wheels. Let me know if there are any specific targets (python versions) you're looking for.

**Comment by jmw182** [comment]
Thanks! I may give it a try. I am somewhat familiar with SWIG (and also don't love it). We use it in an old c++->python project, but we're planning to replace that project with a native python library. Your SWIG wrapper looks much simpler than my pybind11 wrapper, although I was hoping that using pybind11 will be easier to manage dependencies and distribute.

I will be using 64-bit python 3.7, but I already have SWIG and should be able to compile it myself. Thanks again! If I end up finishing my wrapper anyway I can share a link here if you're interested.
